# Generated by Django 5.0.3 on 2024-03-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_painting'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='noofpeoplerated',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
