# Generated by Django 5.0.3 on 2024-04-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_delete_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartforuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('cartcontent', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'cartforuser',
            },
        ),
    ]
